// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user/v1/user_auth.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserMergeAccountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserMergeAccountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserMergeAccountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserMergeAccountRequestMultiError, or nil if none found.
func (m *UserMergeAccountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserMergeAccountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Phone

	// no validation rules for OpenId

	// no validation rules for AppId

	if len(errors) > 0 {
		return UserMergeAccountRequestMultiError(errors)
	}

	return nil
}

// UserMergeAccountRequestMultiError is an error wrapping multiple validation
// errors returned by UserMergeAccountRequest.ValidateAll() if the designated
// constraints aren't met.
type UserMergeAccountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserMergeAccountRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserMergeAccountRequestMultiError) AllErrors() []error { return m }

// UserMergeAccountRequestValidationError is the validation error returned by
// UserMergeAccountRequest.Validate if the designated constraints aren't met.
type UserMergeAccountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserMergeAccountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserMergeAccountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserMergeAccountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserMergeAccountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserMergeAccountRequestValidationError) ErrorName() string {
	return "UserMergeAccountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UserMergeAccountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserMergeAccountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserMergeAccountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserMergeAccountRequestValidationError{}

// Validate checks the field values on UserBingPhoneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserBingPhoneRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserBingPhoneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserBingPhoneRequestMultiError, or nil if none found.
func (m *UserBingPhoneRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserBingPhoneRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OpenId

	// no validation rules for Code

	// no validation rules for AppId

	if len(errors) > 0 {
		return UserBingPhoneRequestMultiError(errors)
	}

	return nil
}

// UserBingPhoneRequestMultiError is an error wrapping multiple validation
// errors returned by UserBingPhoneRequest.ValidateAll() if the designated
// constraints aren't met.
type UserBingPhoneRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserBingPhoneRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserBingPhoneRequestMultiError) AllErrors() []error { return m }

// UserBingPhoneRequestValidationError is the validation error returned by
// UserBingPhoneRequest.Validate if the designated constraints aren't met.
type UserBingPhoneRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserBingPhoneRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserBingPhoneRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserBingPhoneRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserBingPhoneRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserBingPhoneRequestValidationError) ErrorName() string {
	return "UserBingPhoneRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UserBingPhoneRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserBingPhoneRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserBingPhoneRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserBingPhoneRequestValidationError{}

// Validate checks the field values on UserRegRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserRegRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserRegRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserRegRequestMultiError,
// or nil if none found.
func (m *UserRegRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserRegRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sn

	// no validation rules for Code

	// no validation rules for AppId

	if len(errors) > 0 {
		return UserRegRequestMultiError(errors)
	}

	return nil
}

// UserRegRequestMultiError is an error wrapping multiple validation errors
// returned by UserRegRequest.ValidateAll() if the designated constraints
// aren't met.
type UserRegRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserRegRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserRegRequestMultiError) AllErrors() []error { return m }

// UserRegRequestValidationError is the validation error returned by
// UserRegRequest.Validate if the designated constraints aren't met.
type UserRegRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserRegRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserRegRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserRegRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserRegRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserRegRequestValidationError) ErrorName() string { return "UserRegRequestValidationError" }

// Error satisfies the builtin error interface
func (e UserRegRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserRegRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserRegRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserRegRequestValidationError{}
