// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: bff-admin/v1/bff_error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BffErrorReason int32

const (
	BffErrorReason_RECORD_NOT_FOUND      BffErrorReason = 0
	BffErrorReason_RECORD_ALREADY_EXISTS BffErrorReason = 1
	BffErrorReason_BAD_REQUEST           BffErrorReason = 2
	BffErrorReason_SYSTEM_ERROR          BffErrorReason = 3
)

// Enum value maps for BffErrorReason.
var (
	BffErrorReason_name = map[int32]string{
		0: "RECORD_NOT_FOUND",
		1: "RECORD_ALREADY_EXISTS",
		2: "BAD_REQUEST",
		3: "SYSTEM_ERROR",
	}
	BffErrorReason_value = map[string]int32{
		"RECORD_NOT_FOUND":      0,
		"RECORD_ALREADY_EXISTS": 1,
		"BAD_REQUEST":           2,
		"SYSTEM_ERROR":          3,
	}
)

func (x BffErrorReason) Enum() *BffErrorReason {
	p := new(BffErrorReason)
	*p = x
	return p
}

func (x BffErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BffErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_bff_admin_v1_bff_error_reason_proto_enumTypes[0].Descriptor()
}

func (BffErrorReason) Type() protoreflect.EnumType {
	return &file_bff_admin_v1_bff_error_reason_proto_enumTypes[0]
}

func (x BffErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BffErrorReason.Descriptor instead.
func (BffErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_bff_admin_v1_bff_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_bff_admin_v1_bff_error_reason_proto protoreflect.FileDescriptor

var file_bff_admin_v1_bff_error_reason_proto_rawDesc = []byte{
	0x0a, 0x23, 0x62, 0x66, 0x66, 0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x62,
	0x66, 0x66, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x1a,
	0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x82, 0x01, 0x0a, 0x0e, 0x42, 0x66, 0x66, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x10, 0x52, 0x45, 0x43, 0x4f, 0x52,
	0x44, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00, 0x1a, 0x04, 0xa8,
	0x45, 0x94, 0x03, 0x12, 0x1f, 0x0a, 0x15, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x5f, 0x41, 0x4c,
	0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x01, 0x1a, 0x04,
	0xa8, 0x45, 0x90, 0x03, 0x12, 0x15, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55,
	0x45, 0x53, 0x54, 0x10, 0x02, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x12, 0x16, 0x0a, 0x0c, 0x53,
	0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x1a, 0x04, 0xa8,
	0x45, 0xf4, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x64, 0x74, 0x72, 0x69, 0x62, 0x2f,
	0x62, 0x6c, 0x67, 0x2d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62,
	0x66, 0x66, 0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_bff_admin_v1_bff_error_reason_proto_rawDescOnce sync.Once
	file_bff_admin_v1_bff_error_reason_proto_rawDescData = file_bff_admin_v1_bff_error_reason_proto_rawDesc
)

func file_bff_admin_v1_bff_error_reason_proto_rawDescGZIP() []byte {
	file_bff_admin_v1_bff_error_reason_proto_rawDescOnce.Do(func() {
		file_bff_admin_v1_bff_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(file_bff_admin_v1_bff_error_reason_proto_rawDescData)
	})
	return file_bff_admin_v1_bff_error_reason_proto_rawDescData
}

var file_bff_admin_v1_bff_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bff_admin_v1_bff_error_reason_proto_goTypes = []any{
	(BffErrorReason)(0), // 0: admin.v1.BffErrorReason
}
var file_bff_admin_v1_bff_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bff_admin_v1_bff_error_reason_proto_init() }
func file_bff_admin_v1_bff_error_reason_proto_init() {
	if File_bff_admin_v1_bff_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bff_admin_v1_bff_error_reason_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bff_admin_v1_bff_error_reason_proto_goTypes,
		DependencyIndexes: file_bff_admin_v1_bff_error_reason_proto_depIdxs,
		EnumInfos:         file_bff_admin_v1_bff_error_reason_proto_enumTypes,
	}.Build()
	File_bff_admin_v1_bff_error_reason_proto = out.File
	file_bff_admin_v1_bff_error_reason_proto_rawDesc = nil
	file_bff_admin_v1_bff_error_reason_proto_goTypes = nil
	file_bff_admin_v1_bff_error_reason_proto_depIdxs = nil
}
